---
version: '2.4'

services:
  radar-rest-source-auth-backend:
    image: radarbase/radar-rest-source-auth-backend:1.0.0
    depends_on:
      - auth-postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-postgresql:5432/restsourceauth
      - SPRING_DATASOURCE_USERNAME=radarcns
      - SPRING_DATASOURCE_PASSWORD=radarcns
      - REST_SOURCE_AUTHORIZER_SOURCE_CLIENTS_FILE_PATH=app-includes/rest_source_clients_configs.yml
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - APP_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - "8080:8080"
    volumes:
      - ./etc:/app-includes

  auth-postgresql:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=radarcns
      - POSTGRES_PASSWORD=radarcns
      - POSTGRES_DB=restsourceauth

  radar-rest-source-authorizer:
    image: radarbase/radar-rest-source-authorizer:1.0.0
    depends_on:
      - radar-rest-source-auth-backend
      - auth-postgresql
    ports:
      - "3000:80"
